version: '2'

services:

  redis:
    image: redis:4
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 8009:8009
    volumes:
      - ./data/nginx:/data
      - ./nginx_default.conf:/etc/nginx/conf.d/default.conf
    command: |
      /bin/sh -c 'chown nginx:nginx /data && nginx -g "daemon off;"'
